spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.96.106.179:3306/shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /shell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: D:\Program\SpringBoot\shell
#  file: D:\Program\SpringBoot\shell\shell.log
#  level: debug